#ifndef LOADSAVEMERCPROFILE_H
#define LOADSAVEMERCPROFILE_H

#include "Soldier_Profile_Type.h"

// This engine's OWN profile format (savegames, IMP profile cache) -- 39
// inventory slots (NUM_INV_SLOTS). Both bumped by +80 bytes (20 new slots *
// (2-byte inv + 1-byte bInvNumber + 1-byte bInvStatus) = 20*4) for the
// 19->39 slot inventory expansion. The pre-existing 80-byte gap between the
// two constants is unrelated to slot count -- it's UTF-32 (Linux) vs UTF-16
// (Windows) encoding for the 40-char name+nickname fields (40 * (4-2) = 80
// bytes) -- so each grows by its own +80.
#define MERC_PROFILE_SIZE               (796)           /**< This engine's Windows-format Merc profile size */
#define MERC_PROFILE_SIZE_STRAC_LINUX   (876)           /**< This engine's Stracciatella Linux Merc profile size */

// The VANILLA game's OWN, immutable, third-party prof.dat format -- frozen
// forever at 19 inventory slots / 716 bytes. This is NOT our format and must
// NEVER be changed to track NUM_INV_SLOTS or MERC_PROFILE_SIZE -- prof.dat
// ships with the base game and cannot be regenerated by us.
#define VANILLA_PROF_DAT_INV_SLOTS      (19)
#define VANILLA_PROF_DAT_SIZE           (716)

/**
* Extract merc profile from the binary data.
* @param fVanillaProfileFormat true when Src holds a record from the
* immutable, third-party prof.dat (19 inventory slots, VANILLA_PROF_DAT_SIZE
* bytes); false for this engine's own profile format (NUM_INV_SLOTS slots,
* MERC_PROFILE_SIZE/MERC_PROFILE_SIZE_STRAC_LINUX bytes, per stracLinuxFormat).
* Independent from stracLinuxFormat, which only affects name/nickname
* encoding width. */
void ExtractMercProfile(BYTE const* const Src, MERCPROFILESTRUCT& p, bool stracLinuxFormat, UINT32 *checksum, bool const isCorrectlyEncoded, bool fVanillaProfileFormat);

/** Calculates soldier profile checksum. */
UINT32 SoldierProfileChecksum(MERCPROFILESTRUCT const& p);

/** Extract IMP merc profile from file.
* If saved checksum is not correct, exception will be thrown. */
void ExtractImpProfileFromFile(SGPFile *file, INT32 *iProfileId, INT32 *iPortraitNumber, MERCPROFILESTRUCT& p);

void InjectMercProfile(BYTE* Dst, MERCPROFILESTRUCT const&);
void InjectMercProfileIntoFile(HWFILE, MERCPROFILESTRUCT const&);

#endif
