// generated by Fast Light User Interface Designer (fluid) version 1.0309

#ifndef StracciatellaLauncher_h
#define StracciatellaLauncher_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Check_Button.H>

class StracciatellaLauncher {
public:
  StracciatellaLauncher();
  Fl_Double_Window *stracciatellaLauncher;
  Fl_Tabs *tabs;
  Fl_Button *editorButton;
  Fl_Button *playButton;
  Fl_Input *gameDirectoryInput;
  Fl_Button *browseJa2DirectoryButton;
  Fl_Choice *gameVersionInput;
  Fl_Button *guessVersionButton;
  Fl_Input *saveGameDirectoryInput;
  Fl_Button *browseSaveGameDirectoryButton;
  Fl_Browser *enabledModsBrowser;
  Fl_Button *enableModsButton;
  Fl_Button *disableModsButton;
  Fl_Button *moveUpModsButton;
  Fl_Button *moveDownModsButton;
  Fl_Browser *availableModsBrowser;
  Fl_Text_Display *modDetails;
  Fl_Output *gameSettingsOutput;
  Fl_Box *resolutionLabel;
  Fl_Round_Button *autoModeRadio;
  Fl_Round_Button *manualModeRadio;
  Fl_Round_Button *baseResolutionRadio0;
  Fl_Round_Button *baseResolutionRadio1;
  Fl_Box *baseResolutionHint0;
  Fl_Box *baseResolutionHint1;
  Fl_Box *desktopInfoLabel;
  Fl_Check_Button *stretchCheckbox;
  Fl_Check_Button *stretchLaptopCheckbox;
  Fl_Box *invalidResolutionLabel;
  Fl_Choice *scalingModeChoice;
  Fl_Check_Button *fullscreenCheckbox;
  Fl_Check_Button *playSoundsCheckbox;
  Fl_Button *settingsEditorButton;
  Fl_Button *settingsPlayButton;
  Fl_Group *settingsTab;
  Fl_Group *logsTab;
  Fl_Text_Display *logsDisplay;
  Fl_Output *ja2JsonPathOutput;
  Fl_Button *ja2JsonReloadBtn;
  Fl_Button *ja2JsonSaveBtn;
};
#endif
