// generated by Fast Light User Interface Designer (fluid) version 1.0309

#include "StracciatellaLauncher.h"

StracciatellaLauncher::StracciatellaLauncher() {
  { stracciatellaLauncher = new Fl_Double_Window(520, 380, "JA2 Stracciatella Launcher");
    stracciatellaLauncher->user_data((void*)(this));
    { tabs = new Fl_Tabs(0, 0, 520, 350);
      tabs->align(Fl_Align(FL_ALIGN_TOP_RIGHT));
      { Fl_Group* o = new Fl_Group(0, 50, 520, 300, "@> Play  ");
        o->labelsize(16);
        o->labelcolor((Fl_Color)24);
        { editorButton = new Fl_Button(160, 150, 200, 25, "Start Map Editor");
        } // Fl_Button* editorButton
        { playButton = new Fl_Button(160, 185, 200, 55, "Play Ja2 Stracciatella");
        } // Fl_Button* playButton
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 50, 520, 300, "@filenew Data ");
        o->labelcolor((Fl_Color)24);
        o->hide();
        { Fl_Group* o = new Fl_Group(10, 60, 500, 50);
          { gameDirectoryInput = new Fl_Input(20, 75, 440, 30, "JA2 Game Directory:");
            gameDirectoryInput->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            Fl_Group::current()->resizable(gameDirectoryInput);
          } // Fl_Input* gameDirectoryInput
          { browseJa2DirectoryButton = new Fl_Button(470, 75, 30, 30, "@fileopen");
            browseJa2DirectoryButton->tooltip("Choose JA2 game directory.");
          } // Fl_Button* browseJa2DirectoryButton
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(10, 110, 500, 50);
          { gameVersionInput = new Fl_Choice(20, 130, 440, 30, "Game Version:");
            gameVersionInput->down_box(FL_BORDER_BOX);
            gameVersionInput->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            Fl_Group::current()->resizable(gameVersionInput);
          } // Fl_Choice* gameVersionInput
          { guessVersionButton = new Fl_Button(470, 130, 30, 30, "@search");
            guessVersionButton->tooltip("Guess Game Version");
          } // Fl_Button* guessVersionButton
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(10, 265, 500, 25, "resizable");
          o->labeltype(FL_NO_LABEL);
          o->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
          o->end();
          Fl_Group::current()->resizable(o);
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(10, 170, 500, 50);
          { saveGameDirectoryInput = new Fl_Input(20, 185, 440, 30, "Save Game Directory:");
            saveGameDirectoryInput->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            Fl_Group::current()->resizable(saveGameDirectoryInput);
          } // Fl_Input* saveGameDirectoryInput
          { browseSaveGameDirectoryButton = new Fl_Button(470, 185, 30, 30, "@fileopen");
            browseSaveGameDirectoryButton->tooltip("Choose JA2 game directory.");
          } // Fl_Button* browseSaveGameDirectoryButton
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 50, 520, 300, "@-> Mods ");
        o->labelcolor((Fl_Color)24);
        o->hide();
        { Fl_Group* o = new Fl_Group(10, 80, 500, 165);
          { enabledModsBrowser = new Fl_Browser(20, 95, 215, 150, "Enabled Mods:");
            enabledModsBrowser->type(3);
            enabledModsBrowser->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          } // Fl_Browser* enabledModsBrowser
          { enableModsButton = new Fl_Button(245, 95, 30, 30, "@<");
            enableModsButton->tooltip("Enable one or multiple mods.");
            enableModsButton->deactivate();
          } // Fl_Button* enableModsButton
          { disableModsButton = new Fl_Button(245, 135, 30, 30, "@>");
            disableModsButton->tooltip("Disable one or multiple mods.");
            disableModsButton->deactivate();
          } // Fl_Button* disableModsButton
          { moveUpModsButton = new Fl_Button(245, 175, 30, 30, "@2<");
            moveUpModsButton->tooltip("Move mod up in the list and decrease mod priority.");
            moveUpModsButton->deactivate();
          } // Fl_Button* moveUpModsButton
          { moveDownModsButton = new Fl_Button(245, 215, 30, 30, "@8<");
            moveDownModsButton->tooltip("Move mod down in the list and increase mod priority.");
            moveDownModsButton->deactivate();
          } // Fl_Button* moveDownModsButton
          { availableModsBrowser = new Fl_Browser(285, 95, 215, 150, "Disabled Mods:");
            availableModsBrowser->type(3);
            availableModsBrowser->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          } // Fl_Browser* availableModsBrowser
          o->end();
        } // Fl_Group* o
        { modDetails = new Fl_Text_Display(20, 255, 480, 80);
          modDetails->color((Fl_Color)55);
          modDetails->hide();
        } // Fl_Text_Display* modDetails
        { Fl_Box* o = new Fl_Box(17, 55, 480, 20, "Mods listed later in the \"Enabled Mods\" list have higher priority.");
          o->tooltip("Higher priority mods can overwrite changes from lower-priority ones or build \
on their features.");
          o->align(Fl_Align(133|FL_ALIGN_INSIDE));
        } // Fl_Box* o
        o->end();
      } // Fl_Group* o
      { settingsTab = new Fl_Group(0, 50, 520, 300, "@menu Settings ");
        settingsTab->labelcolor((Fl_Color)24);
        settingsTab->hide();
        { Fl_Group* o = new Fl_Group(10, 60, 500, 45);
          { gameSettingsOutput = new Fl_Output(20, 75, 480, 30, "Game Settings:");
            gameSettingsOutput->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            Fl_Group::current()->resizable(gameSettingsOutput);
          } // Fl_Output* gameSettingsOutput
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(10, 105, 500, 75);
          { resolutionLabel = new Fl_Box(17, 113, 300, 18, "Current Screen Resolution:");
            resolutionLabel->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
          } // Fl_Box* resolutionLabel
          { Fl_Group* o = new Fl_Group(149, 135, 140, 22);
            { autoModeRadio = new Fl_Round_Button(149, 135, 60, 22, "Auto");
              autoModeRadio->type(102);
              autoModeRadio->down_box(FL_ROUND_DOWN_BOX);
            } // Fl_Round_Button* autoModeRadio
            { manualModeRadio = new Fl_Round_Button(214, 135, 75, 22, "Manual");
              manualModeRadio->type(102);
              manualModeRadio->down_box(FL_ROUND_DOWN_BOX);
            } // Fl_Round_Button* manualModeRadio
            o->end();
          } // Fl_Group* o
          { Fl_Group* o = new Fl_Group(149, 156, 280, 22);
            { baseResolutionRadio0 = new Fl_Round_Button(149, 156, 90, 22, "1280x720");
              baseResolutionRadio0->type(102);
              baseResolutionRadio0->down_box(FL_ROUND_DOWN_BOX);
            } // Fl_Round_Button* baseResolutionRadio0
            { baseResolutionRadio1 = new Fl_Round_Button(244, 156, 90, 22, "1366x768");
              baseResolutionRadio1->type(102);
              baseResolutionRadio1->down_box(FL_ROUND_DOWN_BOX);
            } // Fl_Round_Button* baseResolutionRadio1
            { // Placeholder for a future base resolution: inactive, not used by the code
              Fl_Round_Button* o = new Fl_Round_Button(339, 156, 90, 22, "1920x1080");
              o->type(102);
              o->down_box(FL_ROUND_DOWN_BOX);
              o->deactivate();
            } // Fl_Round_Button* o
            { // Shows the reason as a tooltip while baseResolutionRadio0 is inactive (inactive widgets show no tooltip)
              baseResolutionHint0 = new Fl_Box(149, 156, 90, 22);
              baseResolutionHint0->hide();
            } // Fl_Box* baseResolutionHint0
            { // Shows the reason as a tooltip while baseResolutionRadio1 is inactive (inactive widgets show no tooltip)
              baseResolutionHint1 = new Fl_Box(244, 156, 90, 22);
              baseResolutionHint1->hide();
            } // Fl_Box* baseResolutionHint1
            o->end();
          } // Fl_Group* o
          { resolutionModeLabel = new Fl_Box(17, 135, 125, 22, "UI Resolution Mode:");
            resolutionModeLabel->tooltip("Selects how the base interface resolution is chosen: automatic adjustment fo\
r the best 16:9 match or manual selection.");
            resolutionModeLabel->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
          } // Fl_Box* resolutionModeLabel
          { baseResolutionLabel = new Fl_Box(17, 156, 125, 22, "UI Base Resolution:");
            baseResolutionLabel->tooltip("Base interface resolution used for scaling in the game.");
            baseResolutionLabel->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
          } // Fl_Box* baseResolutionLabel
          { stretchCheckbox = new Fl_Check_Button(336, 108, 165, 30, "Stretch to Your Screen");
            stretchCheckbox->tooltip("Stretch the game image to fill the whole screen, ignoring its aspect ratio (no\
 black bars).");
            stretchCheckbox->down_box(FL_DOWN_BOX);
          } // Fl_Check_Button* stretchCheckbox
          { stretchLaptopCheckbox = new Fl_Check_Button(336, 135, 165, 18, "Stretch In-Game Laptop");
            stretchLaptopCheckbox->tooltip("Also stretch the In-Game Laptop (640x480) to fill the whole screen. Ignores i\
ts aspect ratio, so the In-Game Laptop looks noticeably wider on widescreen mo\
nitors. Requires \"Stretch to Your Screen\".");
            stretchLaptopCheckbox->down_box(FL_DOWN_BOX);
          } // Fl_Check_Button* stretchLaptopCheckbox
          { Fl_Group* o = new Fl_Group(415, 115, 30, 30, "resizable");
            o->labeltype(FL_NO_LABEL);
            o->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
            o->end();
            Fl_Group::current()->resizable(o);
          } // Fl_Group* o
          { invalidResolutionLabel = new Fl_Box(240, 166, 110, 14, "invalid!");
            invalidResolutionLabel->labelfont(1);
            invalidResolutionLabel->labelcolor((Fl_Color)1);
            invalidResolutionLabel->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
          } // Fl_Box* invalidResolutionLabel
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(10, 190, 500, 55);
          o->tooltip("Choose a scaling mode to stretch the game video to fit the screen. Linear and\
 Near-Perfect modes stretch the video to match any window sizes, but the image\
 may look blurred. Pixel-Perfect can only scale up by integer (1x, 2x and so o\
n) but gives sharp images.");
          { scalingModeChoice = new Fl_Choice(20, 205, 480, 30, "Scaling Mode:");
            scalingModeChoice->down_box(FL_BORDER_BOX);
            scalingModeChoice->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            Fl_Group::current()->resizable(scalingModeChoice);
          } // Fl_Choice* scalingModeChoice
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(10, 240, 500, 65);
          { fullscreenCheckbox = new Fl_Check_Button(20, 245, 95, 30, "Fullscreen");
            fullscreenCheckbox->tooltip("Check to run in a borderless full-screen window");
            fullscreenCheckbox->down_box(FL_DOWN_BOX);
          } // Fl_Check_Button* fullscreenCheckbox
          { playSoundsCheckbox = new Fl_Check_Button(20, 275, 109, 30, "Play Sounds");
            playSoundsCheckbox->down_box(FL_DOWN_BOX);
            playSoundsCheckbox->value(1);
          } // Fl_Check_Button* playSoundsCheckbox
          o->end();
        } // Fl_Group* o
        { settingsEditorButton = new Fl_Button(165, 311, 200, 25, "Start Map Editor");
        } // Fl_Button* settingsEditorButton
        { settingsPlayButton = new Fl_Button(165, 245, 200, 55, "Play Ja2 Stracciatella");
        } // Fl_Button* settingsPlayButton
        settingsTab->end();
      } // Fl_Group* settingsTab
      { logsTab = new Fl_Group(0, 50, 520, 300, "@square Logs");
        logsTab->labelcolor((Fl_Color)24);
        logsTab->hide();
        { logsDisplay = new Fl_Text_Display(20, 95, 480, 250, "You can view the logs of the latest JA2 Stracciatella execution here. If you \
want to report a bug, please include them in your bug report.");
          logsDisplay->box(FL_DOWN_BOX);
          logsDisplay->align(Fl_Align(133));
          Fl_Group::current()->resizable(logsDisplay);
        } // Fl_Text_Display* logsDisplay
        logsTab->end();
      } // Fl_Group* logsTab
      tabs->end();
      Fl_Group::current()->resizable(tabs);
    } // Fl_Tabs* tabs
    { Fl_Group* o = new Fl_Group(0, 350, 465520, 30);
      { ja2JsonPathOutput = new Fl_Output(0, 350, 460, 30);
        ja2JsonPathOutput->tooltip("Path to stracciatella engine options");
        ja2JsonPathOutput->color(FL_BACKGROUND_COLOR);
        ja2JsonPathOutput->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
        Fl_Group::current()->resizable(ja2JsonPathOutput);
      } // Fl_Output* ja2JsonPathOutput
      { ja2JsonReloadBtn = new Fl_Button(460, 350, 30, 30, "@reload");
        ja2JsonReloadBtn->tooltip("Reload stracciatella engine options");
        ja2JsonReloadBtn->box(FL_THIN_UP_BOX);
        ja2JsonReloadBtn->labelcolor(FL_INACTIVE_COLOR);
      } // Fl_Button* ja2JsonReloadBtn
      { ja2JsonSaveBtn = new Fl_Button(490, 350, 30, 30, "@filesave");
        ja2JsonSaveBtn->tooltip("Save stracciatella engine options");
        ja2JsonSaveBtn->box(FL_THIN_UP_BOX);
        ja2JsonSaveBtn->labelcolor(FL_INACTIVE_COLOR);
      } // Fl_Button* ja2JsonSaveBtn
      o->end();
    } // Fl_Group* o
    stracciatellaLauncher->size_range(520, 390);
    stracciatellaLauncher->end();
  } // Fl_Double_Window* stracciatellaLauncher
}
